// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIlzZmDA9fXiVLct27lZeAmEOnoX-5P0',
    appId: '1:186129001142:web:6644fe6769fb2ac1099417',
    messagingSenderId: '186129001142',
    projectId: 'fitness-coach-hack-davis',
    authDomain: 'fitness-coach-hack-davis.firebaseapp.com',
    storageBucket: 'fitness-coach-hack-davis.firebasestorage.app',
    measurementId: 'G-HZ1FJ59B3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJNhJOLV3GGyvN4abVsfJYsFAs1dhM4s',
    appId: '1:186129001142:android:8b941ac94db2774a099417',
    messagingSenderId: '186129001142',
    projectId: 'fitness-coach-hack-davis',
    storageBucket: 'fitness-coach-hack-davis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzQfPR4NhoX_OByO7Pgf-qaxw6oG2Ej68',
    appId: '1:186129001142:ios:5cebc07612b18234099417',
    messagingSenderId: '186129001142',
    projectId: 'fitness-coach-hack-davis',
    storageBucket: 'fitness-coach-hack-davis.firebasestorage.app',
    iosBundleId: 'com.maxwelltan.fitnessCoachApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzQfPR4NhoX_OByO7Pgf-qaxw6oG2Ej68',
    appId: '1:186129001142:ios:90cc0d499f092187099417',
    messagingSenderId: '186129001142',
    projectId: 'fitness-coach-hack-davis',
    storageBucket: 'fitness-coach-hack-davis.firebasestorage.app',
    iosBundleId: 'com.example.fitnessCoachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiIlzZmDA9fXiVLct27lZeAmEOnoX-5P0',
    appId: '1:186129001142:web:a7c42a07083cb28d099417',
    messagingSenderId: '186129001142',
    projectId: 'fitness-coach-hack-davis',
    authDomain: 'fitness-coach-hack-davis.firebaseapp.com',
    storageBucket: 'fitness-coach-hack-davis.firebasestorage.app',
    measurementId: 'G-7BRX2V27WG',
  );
}
